import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author Abdullah Bestil
 */
public class GuessGame extends javax.swing.JFrame {

    /**
     * Creates new form GuessGame2
     */
    public GuessGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main1 = new Main();
        guessLabel = new javax.swing.JLabel();
        tryButton = new javax.swing.JButton();
        answerLabel = new javax.swing.JLabel();
        guessedNumberField = new javax.swing.JTextField();
        numberOfTrialsLabel = new javax.swing.JLabel();
        previousTrialsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guess Game");

        guessLabel.setText("Enter your guess between 1 and 300 here;");

        tryButton.setText("Try!");
        tryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryButtonActionPerformed(evt);
            }
        });

        answerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        answerLabel.setName(""); // NOI18N

        guessedNumberField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guessedNumberField.setToolTipText("");

        numberOfTrialsLabel.setText("Number of trials = 0");

        previousTrialsLabel.setText("Last 5 trials = ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(guessLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guessedNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfTrialsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(previousTrialsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(answerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(guessLabel)
                .addGap(13, 13, 13)
                .addComponent(guessedNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(previousTrialsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numberOfTrialsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Defines variables
    Random rand = new Random();
    int numberToGuess = rand.nextInt(301);
    int numberOfTrials = 0;
    int resetGame = 0;
    int guessedNumber;
    ArrayList<Integer> previousTrials = new ArrayList<>();
    int IntervalLenght = 300;
    
    //Reset function resets the game
    public void resetGame(){
        resetGame = 0;
        tryButton.setText("Try!");
        guessedNumberField.setText("");
        answerLabel.setText("");
        numberOfTrials = 0;
        numberToGuess = rand.nextInt(IntervalLenght+1);
        previousTrials.clear();
    }
    
    //
    
    //Button actions
    private void tryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryButtonActionPerformed

        //If the user finds the correct answer and hits reset button, this part resets the game.
        if (resetGame == 1) {
            resetGame();
        } else {

            //With this try-catch block we give a pop-up message to the user that s/he needs to enter a number.
            try {
                guessedNumber = Integer.parseInt(
                        this.guessedNumberField.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please enter a number!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            numberOfTrials++;
            //This block fills the arrayList to show the last 5 guesses to the user.
            if (numberOfTrials > 5) {
                previousTrials.remove(0);
            }
            previousTrials.add(guessedNumber);

            //This big block shows different mesages to the user according to how close the guess to the secret answer.
            if (guessedNumber > 0 && guessedNumber < 301) {

                if (guessedNumber == numberToGuess) {
                    this.answerLabel.setText("Congrats! You found the answer in " + numberOfTrials + " trials.");
                    tryButton.setText("Reset!");
                    resetGame = 1;
                } else if (guessedNumber < numberToGuess - 30) {
                    this.answerLabel.setText("<html><div style='text-align: center;'>Your guess is much smaller than the secret answer, <br/> guess a much bigger number.</div></html>");
                } else if (guessedNumber > numberToGuess - 30 && guessedNumber < numberToGuess - 5) {
                    this.answerLabel.setText("<html><div style='text-align: center;'>Your guess is smaller than the secret answer, <br/> guess a bigger number.</div></html>");
                } else if (guessedNumber > numberToGuess - 5 && guessedNumber < numberToGuess) {
                    this.answerLabel.setText("<html><div style='text-align: center;'>Your guess is very close to the secret answer, <br/> guess a little bigger number.</div></html>");
                } else if (guessedNumber > numberToGuess && guessedNumber < numberToGuess + 5) {
                    this.answerLabel.setText("<html><div style='text-align: center;'>Your guess is very close to the secret answer, <br/> guess a little smaller number.</div></html>");
                } else if (guessedNumber > numberToGuess + 5 && guessedNumber < numberToGuess + 30) {
                    this.answerLabel.setText("<html><div style='text-align: center;'>Your guess is bigger than the secret answer, <br/> guess a smaller number.</div></html>");
                } else if (guessedNumber > numberToGuess + 30) {
                    this.answerLabel.setText("<html><div style='text-align: center;'>Your guess is much bigger than the secret answer, <br/> guess a much smaller number.</div></html>");
                }

            } else {
                this.answerLabel.setText("<html><div style='text-align: center;'>Your guess is not even in the range, <br/> please try to guess a number between 1 and 300.</div></html>");
            }

        }
        //Prints the number of trials.
        numberOfTrialsLabel.setText("Number of trials = " + numberOfTrials);

        //Adjusts the the last 5 trials or the user
        String previousTrialsString = previousTrials.toString();
        previousTrialsString = previousTrialsString.replace("[", "");
        previousTrialsString = previousTrialsString.replace("]", "");

        previousTrialsLabel.setText("Last 5 trials = " + previousTrialsString);
    }//GEN-LAST:event_tryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GuessGame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLabel;
    private javax.swing.JLabel guessLabel;
    private javax.swing.JTextField guessedNumberField;
    private Main main1;
    private javax.swing.JLabel numberOfTrialsLabel;
    private javax.swing.JLabel previousTrialsLabel;
    private javax.swing.JButton tryButton;
    // End of variables declaration//GEN-END:variables
}
